# 15 Years of SSC CGL Previous Year Questions Database
# This is a STARTER TEMPLATE. Replace with verified questions you have legal permission to use.

PYQ_QUESTIONS = [
    # 2023
    {"year":2023,"month":"Dec","subject":"quant","topic":"Percentage","q_en":"If 30% of A is equal to 40% of B, then A:B is?","q_hi":"यदि A का 30% = B का 40% है, तो A:B है?","options":["3:4","4:3","2:3","3:2"],"answer":1,"exp_en":"30A = 40B => A/B = 40/30 = 4/3","exp_hi":"30A = 40B => A/B = 40/30 = 4/3"},
    {"year":2023,"month":"Dec","subject":"quant","topic":"Average","q_en":"Average of 5 numbers is 24. If one number is removed, average becomes 20. What is the removed number?","q_hi":"5 संख्याओं का औसत 24 है। यदि एक संख्या हटा दी जाए, तो औसत 20 हो जाता है। हटाई गई संख्या क्या है?","options":["40","44","48","50"],"answer":0,"exp_en":"Sum of 5 = 5×24=120. Sum of 4 = 4×20=80. Removed = 120-80=40","exp_hi":"5 का योग = 5×24=120। 4 का योग = 4×20=80। हटाई गई = 120-80=40"},
    {"year":2023,"month":"Dec","subject":"reasoning","topic":"Analogy","q_en":"Bird : Nest :: ? : Web","q_hi":"पक्षी : घोंसला :: ? : जाला","options":["Spider","Ant","Bee","Butterfly"],"answer":0,"exp_en":"Bird makes nest like Spider makes web","exp_hi":"पक्षी घोंसला बनाता है जैसे मकड़ी जाला बनाती है"},
    {"year":2023,"month":"Dec","subject":"english","topic":"Vocabulary","q_en":"Antonym of 'Benign'?","q_hi":"'Benign' का विलोम?","options":["Kind","Malignant","Good","Gentle"],"answer":1,"exp_en":"Benign means kind/good. Malignant is opposite.","exp_hi":"Benign का अर्थ है अच्छा/दयालु। Malignant इसके विपरीत है।"},
    {"year":2023,"month":"Dec","subject":"gk","topic":"History","q_en":"In which year did Vasco da Gama reach India?","q_hi":"वास्को डा गामा भारत में कब पहुंचे?","options":["1498","1500","1505","1510"],"answer":0,"exp_en":"Vasco da Gama reached Calicut in 1498","exp_hi":"वास्को डा गामा 1498 में कालीकट पहुंचे"},
    
    # 2022
    {"year":2022,"month":"Dec","subject":"quant","topic":"Ratio","q_en":"If A:B = 3:2 and B:C = 4:5, find A:B:C","q_hi":"यदि A:B = 3:2 और B:C = 4:5, तो A:B:C ज्ञात करें","options":["6:4:5","12:8:10","6:4:10","12:4:5"],"answer":0,"exp_en":"Make B equal: A:B = 3:2 × 2/2 = 6:4, B:C = 4:5. So A:B:C = 6:4:5","exp_hi":"B को बराबर करें: A:B = 3:2 × 2/2 = 6:4, B:C = 4:5। तो A:B:C = 6:4:5"},
    {"year":2022,"month":"Dec","subject":"quant","topic":"Simple Interest","q_en":"SI on Rs 1000 at 5% p.a. for 2 years?","q_hi":"रु 1000 पर 5% वार्षिक दर से 2 साल का साधारण ब्याज?","options":["Rs 100","Rs 150","Rs 200","Rs 250"],"answer":0,"exp_en":"SI = (P×R×T)/100 = (1000×5×2)/100 = 100","exp_hi":"SI = (P×R×T)/100 = (1000×5×2)/100 = 100"},
    {"year":2022,"month":"Dec","subject":"reasoning","topic":"Series","q_en":"2, 5, 10, 17, 26, ?","q_hi":"2, 5, 10, 17, 26, ?","options":["35","37","39","41"],"answer":1,"exp_en":"Differences: 3,5,7,9,11. Next is 26+11=37","exp_hi":"अंतर: 3,5,7,9,11। अगला 26+11=37"},
    {"year":2022,"month":"Dec","subject":"english","topic":"Grammar","q_en":"Choose correct: 'Neither A nor B __ correct.'","q_hi":"सही चुनें: 'Neither A nor B __ सही है।'","options":["are","is","were","has been"],"answer":1,"exp_en":"Neither...nor with singular subject takes singular verb","exp_hi":"Neither...nor के साथ एकवचन verb आता है"},
    {"year":2022,"month":"Dec","subject":"gk","topic":"Science","q_en":"Boiling point of water is?","q_hi":"पानी का क्वथनांक है?","options":["90°C","100°C","110°C","120°C"],"answer":1,"exp_en":"Water boils at 100°C at sea level","exp_hi":"समुद्र तल पर पानी 100°C पर उबलता है"},
    
    # 2021
    {"year":2021,"month":"Aug","subject":"quant","topic":"Percentage","q_en":"What percent of 90 is 27?","q_hi":"90 का कितना प्रतिशत 27 है?","options":["20%","25%","30%","35%"],"answer":2,"exp_en":"(27/90)×100 = 30%","exp_hi":"(27/90)×100 = 30%"},
    {"year":2021,"month":"Aug","subject":"reasoning","topic":"Logic","q_en":"If SMART is coded as 19-13-1-18-20, how is BRAIN coded?","q_hi":"यदि SMART को 19-13-1-18-20 से कोडित किया जाता है, तो BRAIN को कैसे कोडित किया जाता है?","options":["2-18-1-9-14","2-1-18-9-14","1-2-18-9-14","18-2-1-9-14"],"answer":0,"exp_en":"A=1, B=2, R=18, A=1, I=9, N=14. BRAIN = 2-18-1-9-14","exp_hi":"A=1, B=2, R=18, A=1, I=9, N=14। BRAIN = 2-18-1-9-14"},
    {"year":2021,"month":"Aug","subject":"english","topic":"Spelling","q_en":"Which is correctly spelled?","q_hi":"कौन सा सही spelled है?","options":["Occassion","Occasion","Ocasion","Occation"],"answer":1,"exp_en":"Occasion has double C and double S","exp_hi":"Occasion में दो C और दो S होते हैं"},
    {"year":2021,"month":"Aug","subject":"gk","topic":"Geography","q_en":"Which is the highest mountain in the world?","q_hi":"दुनिया का सबसे ऊंचा पहाड़ कौन सा है?","options":["K2","Mount Everest","Kilimanjaro","Denali"],"answer":1,"exp_en":"Mount Everest is 8849 meters high","exp_hi":"Mount Everest 8849 मीटर ऊंचा है"},
    
    # 2020
    {"year":2020,"month":"Oct","subject":"quant","topic":"Profit-Loss","q_en":"CP = 100, SP = 120, Profit % = ?","q_hi":"क्रय मूल्य = 100, विक्रय मूल्य = 120, लाभ % = ?","options":["15%","20%","25%","30%"],"answer":1,"exp_en":"Profit% = ((120-100)/100)×100 = 20%","exp_hi":"लाभ% = ((120-100)/100)×100 = 20%"},
    {"year":2020,"month":"Oct","subject":"reasoning","topic":"Venn Diagram","q_en":"All birds are animals. Some animals are birds. Which is true?","q_hi":"सभी पक्षी जानवर हैं। कुछ जानवर पक्षी हैं। कौन सा सच है?","options":["All animals are birds","Some birds are not animals","All statements are true","Both are true"],"answer":3,"exp_en":"First and second statements are both true","exp_hi":"पहला और दूसरा दोनों सच हैं"},
    {"year":2020,"month":"Oct","subject":"english","topic":"Comprehension","q_en":"Main idea of passage is?","q_hi":"passage का मुख्य विचार है?","options":["A","B","C","D"],"answer":0,"exp_en":"Based on passage context","exp_hi":"passage के संदर्भ के आधार पर"},
    {"year":2020,"month":"Oct","subject":"gk","topic":"Polity","q_en":"How many Lok Sabha seats in India?","q_hi":"भारत में लोकसभा की सीटें कितनी हैं?","options":["530","545","550","543"],"answer":2,"exp_en":"India has 543 Lok Sabha seats","exp_hi":"भारत में 543 लोकसभा सीटें हैं"},
]

NOTES_DATA = [
    {"subject":"quant","topic":"Percentage","title_en":"Percentage Basics & Applications","title_hi":"प्रतिशत की मूल बातें और अनुप्रयोग","body_en":"Formula: Percentage = (Part/Whole)×100. Key topics: profit-loss, discount, population increase, simple interest. Practice: 50+ questions. Focus on word problems.","body_hi":"सूत्र: प्रतिशत = (भाग/कुल)×100। मुख्य विषय: लाभ-हानि, छूट, जनसंख्या वृद्धि, साधारण ब्याज। अभ्यास: 50+ प्रश्न। शब्द समस्याओं पर ध्यान दें।"},
    {"subject":"quant","topic":"Ratio & Proportion","title_en":"Ratio, Proportion & Partnership","title_hi":"अनुपात, समानुपात और साझेदारी","body_en":"Key formulas: A:B:C finding, direct proportion, inverse proportion. Practice: combining ratios, work problems, profit sharing. Solve 100+ problems.","body_hi":"मुख्य सूत्र: A:B:C ज्ञात करना, सीधा अनुपात, व्युत्क्रम अनुपात। अभ्यास: अनुपातों को जोड़ना, कार्य समस्याएं, लाभ साझाकरण। 100+ समस्याएं हल करें।"},
    {"subject":"reasoning","topic":"Series","title_en":"Number & Letter Series","title_hi":"संख्या और अक्षर श्रृंखला","body_en":"Patterns: arithmetic, geometric, Fibonacci, second differences. Check: +, ×, square, cube, alternating. Practice: 200+ series problems. Time: 1 min per Q.","body_hi":"पैटर्न: अंकगणित, ज्यामितीय, Fibonacci, दूसरा अंतर। जांचें: +, ×, वर्ग, घन, वैकल्पिक। अभ्यास: 200+ श्रृंखला समस्याएं। समय: Q प्रति 1 मिनट।"},
    {"subject":"english","topic":"Grammar","title_en":"Essential English Grammar","title_hi":"आवश्यक अंग्रेजी व्याकरण","body_en":"Topics: Tenses (12), Voice, Mood, Subject-Verb Agreement, Articles, Prepositions. Rules + exceptions. Practice: 500+ MCQs. Daily 1 hour.","body_hi":"विषय: काल (12), Voice, Mood, कर्ता-क्रिया समझौता, आर्टिकल, पूर्वसर्ग। नियम + अपवाद। अभ्यास: 500+ MCQs। दैनिक 1 घंटा।"},
    {"subject":"gk","topic":"History","title_en":"Indian History Overview","title_hi":"भारतीय इतिहास का सारांश","body_en":"Periods: Ancient (2300 BCE-800 BCE), Medieval (800-1757), Modern (1757-1947). Key: Vedic, Mauryan, Gupta, Mughal, British. Revise: freedom struggle, dates, personalities.","body_hi":"अवधि: प्राचीन (2300 BCE-800 BCE), मध्यकालीन (800-1757), आधुनिक (1757-1947)। मुख्य: वैदिक, मौर्य, गुप्त, मुगल, ब्रिटिश। दोहराएं: स्वतंत्रता संग्राम, तारीखें, व्यक्तित्व।"},
]
